steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 'europe-west1-docker.pkg.dev/viral-460106/manual-build-repo/app-via-clean-yaml:latest',
    '-t', 'europe-west1-docker.pkg.dev/viral-460106/manual-build-repo/app-via-clean-yaml:$COMMIT_SHA',
    '.'
  ]
  id: 'Build Docker Image'

# Push the tags
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-west1-docker.pkg.dev/viral-460106/manual-build-repo/app-via-clean-yaml:latest']
  waitFor: ['Build Docker Image']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-west1-docker.pkg.dev/viral-460106/manual-build-repo/app-via-clean-yaml:$COMMIT_SHA']
  waitFor: ['Build Docker Image']

images:
- 'europe-west1-docker.pkg.dev/viral-460106/manual-build-repo/app-via-clean-yaml:$COMMIT_SHA'
- 'europe-west1-docker.pkg.dev/viral-460106/manual-build-repo/app-via-clean-yaml:latest'
